### ISSUE TITLE
Can't run cent init

### ISSUE THREAD

**Issue by vanzybanez** [xm1k3/cent#37] opened 2023-05-22 13:29 UTC
- I have installed go through brew
- Verified that the go was installed properly [current file path: Users/name/go
- Redirected to Users/name/go/bin/cent 
- when running cent the cli responds "zsh: command not found: cent"

Can you help me 'bout this please thank you

Device Used: Macbook Pro 2020 M1
Current OS version: Ventura 13.3

**Comment by xm1k3** [comment] 2023-06-20 20:49
Thank you for getting back to me. I apologize for the delayed response. To clarify, I would like to ask if the error you reported in the issue is still occurring. If you have encountered the same problem again or if there are any new issues you would like to address, please provide me with the details. I'll be glad to assist you further.

**Comment by xm1k3** [comment] 2023-08-22 22:46
Hi @vanzybanez ,
closing this issue as I haven't received a reply, if there is any news feel free to reopen this issue again

**Closed by xm1k3** 2023-08-22 22:46 UTC

**Comment by unauthxrized** [comment] 2024-07-12 23:53
I have same problem:(
