### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by Fanstasy** [xm1k3/cent#36] opened 2023-04-07 07:34 UTC
when i search cent init /home/.cent.yaml , its showing like i/o timeout
please sol this problems

**Comment by xm1k3** [comment] 2023-06-20 20:44
Hi @Fanstasy,
Could you please provide more information about the specific error message or any additional context? This would help in identifying the cause of the "I/O timeout" issue and providing a solution.

Thanks

**Comment by xm1k3** [comment] 2023-08-22 22:45
Hi @Fanstasy,
closing this issue as I haven't received a reply, if there is any news feel free to reopen this issue again

**Closed by xm1k3** 2023-08-22 22:45 UTC
