### ISSUE TITLE
ERROR!! go/pkg/mod/github.com/xm1k3/cent@v0.0.0-20210805070318-b4084525c87e/pkg/jobs/jobs.go:7:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)

### ISSUE THREAD

**Issue by d4715** [xm1k3/cent#6] opened 2021-08-05 11:32 UTC
hello there,

when i run this command GO111MODULE=on go get -u github.com/xm1k3/cent for install cent in my kali linux 
that time i got this error package io/fs is not in GOROOT
here is the full detail
GO111MODULE=on go get -u github.com/xm1k3/cent

go: github.com/xm1k3/cent upgrade => v0.0.0-20210805070318-b4084525c87e
go: golang.org/x/text upgrade => v0.3.6
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/mattn/go-isatty upgrade => v0.0.13
go: golang.org/x/sys upgrade => v0.0.0-20210630005230-0f9fa26af87c
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/fatih/color upgrade => v1.12.0
go: github.com/mitchellh/mapstructure upgrade => v1.4.1
go: github.com/mitchellh/go-homedir upgrade => v1.1.0
go: github.com/spf13/cast upgrade => v1.4.0
go/pkg/mod/github.com/xm1k3/cent@v0.0.0-20210805070318-b4084525c87e/pkg/jobs/jobs.go:7:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)

 
here i attached screen shot 
![1](https://user-images.githubusercontent.com/11803332/128342866-0c2f45e9-2902-49b1-a452-5c11e564b979.JPG)

some details about kali linux 

1) i run kali linux in vmware workstation14.1.3 build-9474260 with latest update of kali linux

2)go version go1.15.9 linux/amd64

3)cat /etc/*release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.2"
VERSION_ID="2021.2"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

so how can i solve this issue ?
please guide me .
Thanks

**Comment by xm1k3** [comment] 2021-08-05 13:05
Hi,
the problem here is in the version of Golang you have installed on your pc, on the documentation of the `io/fs` library there is written that you must have `golang version 1.16.6`
- see here: https://pkg.go.dev/io/fs

To install the v1.16 follow this steps:
```
> wget -c https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
> sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
> export PATH=$PATH:/usr/local/go/bin
> go version
```
Reference: https://golang.org/doc/install

Let me know if this works

**Comment by d4715** [comment] 2021-08-06 14:16
Hello There, 
Thanks for help!!! I just follow your steps and my problem solved!!
one more time thank you.
i have one question for you, can we use this tool on Ubuntu?
 if yes so which Ubuntu OS  version fit for this tool.

Thanks ,

**Comment by xm1k3** [comment] 2021-08-06 15:32
Yes, you can use this tool on any Linux distribution
Personally i use it on `Ubuntu 20.04`

Since the problem is solved, I will also close this issue

**Closed by xm1k3** 2021-08-06 15:32 UTC
Labels: wontfix

**Comment by TaqwaGuy** [comment] 2021-11-18 23:06
Hey
I have go version 17.3(latest) and I was faced with this error, below when installing the tool.
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/mattn/go-isatty v0.0.13
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/spf13/viper v1.9.0
go: downloading github.com/mitchellh/mapstructure v1.4.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/pelletier/go-toml v1.9.3
go: downloading github.com/spf13/cast v1.4.0
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/mattn/go-colorable v0.1.11
go: downloading golang.org/x/text v0.3.7
go: downloading golang.org/x/sys v0.0.0-20211117180635-dee7805ff2e1
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'

can you please help in debugging
